# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mysql2-foreign_key_constraints"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["labocho"]
  s.date = "2012-07-09"
  s.description = "Add foreign key constraints helper methods to ActiveRecord migration for mysql2 adapter."
  s.email = "labocho@penguinlab.jp"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/foreign_key_constraints/constraint.rb",
    "lib/foreign_key_constraints/schema_dumper.rb",
    "lib/foreign_key_constraints/statement.rb",
    "lib/foreign_key_constraints/table.rb",
    "lib/foreign_key_constraints/version.rb",
    "lib/mysql2-foreign_key_constraints.rb",
    "spec/database.yml",
    "spec/mysql2-foreign_key_constraints_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/labocho/mysql2-foreign_key_constraints"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Add foreign key constraints helper methods to ActiveRecord migration for mysql2 adapter."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.6"])
      s.add_runtime_dependency(%q<mysql2>, [">= 0.2.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0.6"])
      s.add_dependency(%q<mysql2>, [">= 0.2.7"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0.6"])
    s.add_dependency(%q<mysql2>, [">= 0.2.7"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

